name: Get and set Tutor configuration
description: 'Get Tutor configuration values and set them as environment variables'

inputs:
    STRAIN_PATH:
        description: 'The path within the repository for strains'
        required: true
        type: string

runs:
  using: 'composite'
  steps:

    - name: Install Python and dependencies
      run: |
        pip install pyyaml
      shell: bash

    - name: Get Tutor Configurations from config.yml and set them as an environment variable
      env:
        REQUIRED_KEYS: TUTOR_VERSION TUTOR_APP_NAME
        OPTIONAL_KEYS: DOCKER_REGISTRY
        CONFIG_FILE: strains/${{ inputs.STRAIN_PATH }}/config.yml
        SCRIPT_PATH: picasso/.github/workflows/actions/get-tutor-config/get_tutor_config.py
      run: |
        env_vars=$(python $SCRIPT_PATH --config-file $CONFIG_FILE --required-keys $REQUIRED_KEYS --optional-keys $OPTIONAL_KEYS)
        if [ $? -ne 0 ]; then
          echo "::error Failed to get Tutor configurations: $env_vars"
          exit 1
        fi
        echo "$env_vars" >> $GITHUB_ENV
      shell: bash
